# Generated by Django 4.2.13 on 2024-07-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="url",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
