# Generated by Django 4.2.13 on 2024-07-05 04:35

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_book_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
