# Generated by Django 4.2.13 on 2024-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_book_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
