# Generated by Django 4.2.13 on 2024-07-05 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_book_discount_alter_book_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
    ]
