# Generated by Django 4.2.13 on 2024-07-05 15:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_remove_book_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="discount",
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
