# Generated by Django 4.2.13 on 2024-07-05 15:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_remove_book_discount_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
